<template>
  <div>
    <p style="text-align: center">工作状态</p>
    <el-table
      id="table"
      :data="fromdatas"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="start"
        label="start">
      </el-table-column>
      <el-table-column
        prop="counter"
        label="counter">
      </el-table-column>
      <el-table-column
        prop="hour"
        label="hour">
      </el-table-column>
      <el-table-column
        prop="minute"
        label="minute">
      </el-table-column>
      <el-table-column
        prop="second"
        label="second">
      </el-table-column>
      <el-table-column
        prop="millisecond"
        label="millisecond">
      </el-table-column>
      <el-table-column
        prop="kashiStart"
        label="kashiStart">
      </el-table-column>
      <el-table-column
        prop="kashiCounter"
        label="kashiCounter">
      </el-table-column>
      <el-table-column
        prop="kashiHour"
        label="kashiHour">
      </el-table-column>
      <el-table-column
        prop="kashiMinute"
        label="kashiMinute">
      </el-table-column>
      <el-table-column
        prop="kashiSecond"
        label="kashiSecond">
      </el-table-column>
      <el-table-column
        prop="kashiMillisecond"
        label="kashiMillisecond">
      </el-table-column>
      <el-table-column
        prop="kashiReverse"
        label="kashiReverse">
      </el-table-column>
      <el-table-column
        prop="kashiAzimuth"
        label="kashiAzimuth">
      </el-table-column>
      <el-table-column
        prop="kashiPitchAngle"
        label="kashiPitchAngle">
      </el-table-column>
      <el-table-column
        prop="kashiReverse1"
        label="kashiReverse1">
      </el-table-column>
      <el-table-column
        prop="kashiTemperature"
        label="kashiTemperature">
      </el-table-column>
      <el-table-column
        prop="kashiReverse2"
        label="kashiReverse2">
      </el-table-column>
      <el-table-column
        prop="kashiEnd"
        label="kashiEnd">
      </el-table-column>
      <el-table-column
        prop="sanyaStart"
        label="sanyaStart">
      </el-table-column>
      <el-table-column
        prop="sanyaCounter"
        label="sanyaCounter">
      </el-table-column>
      <el-table-column
        prop="sanyaHour"
        label="sanyaHour">
      </el-table-column>
      <el-table-column
        prop="sanyaMinute"
        label="sanyaMinute">
      </el-table-column>
      <el-table-column
        prop="sanyaSecond"
        label="sanyaSecond">
      </el-table-column>
      <el-table-column
        prop="sanyaiMillisecond"
        label="sanyaiMillisecond">
      </el-table-column>
      <el-table-column
        prop="sanyaReverse"
        label="sanyaReverse">
      </el-table-column>
      <el-table-column
        prop="sanyaAzimuth"
        label="sanyaAzimuth">
      </el-table-column>
      <el-table-column
        prop="sanyaPitchAngle"
        label="sanyaPitchAngle">
      </el-table-column>
      <el-table-column
        prop="sanyaReverse1"
        label="sanyaReverse1">
      </el-table-column>
      <el-table-column
        prop="sanyaTemperature"
        label="sanyaTemperature">
      </el-table-column>
      <el-table-column
        prop="sanyaReverse2"
        label="sanyaReverse2">
      </el-table-column>
      <el-table-column
        prop="sanyaEnd"
        label="sanyaEnd">
      </el-table-column>

      <el-table-column
        prop="jilinStart"
        label="jilinStart">
      </el-table-column>
      <el-table-column
        prop="jilinCounter"
        label="jilinCounter">
      </el-table-column>
      <el-table-column
        prop="jilinHour"
        label="jilinHour">
      </el-table-column>
      <el-table-column
        prop="jilinMinute"
        label="jilinMinute">
      </el-table-column>
      <el-table-column
        prop="jilinSecond"
        label="jilinSecond">
      </el-table-column>
      <el-table-column
        prop="jilinMillisecond"
        label="jilinMillisecond">
      </el-table-column>
      <el-table-column
        prop="jilinReverse"
        label="jilinReverse">
      </el-table-column>
      <el-table-column
        prop="jilinAzimuth"
        label="jilinAzimuth">
      </el-table-column>
      <el-table-column
        prop="jilinPitchAngle"
        label="jilinPitchAngle">
      </el-table-column>
      <el-table-column
        prop="jilinReverse1"
        label="jilinReverse1">
      </el-table-column>
      <el-table-column
        prop="jilinTemperature"
        label="jilinTemperature">
      </el-table-column>
      <el-table-column
        prop="jilinReverse2"
        label="jilinReverse2">
      </el-table-column>
      <el-table-column
        prop="jilinEnd"
        label="jilinEnd">
      </el-table-column>
      <el-table-column
        prop="end"
        label="end">
      </el-table-column>
    </el-table>
  </div>
</template>
<script>
export default {
  props: ['fromdatas'],
  name: 'VLBIWorkState',
  data () {
    return {
    }
  }
}
</script>
<style scoped>

</style>
