<template>
  <div>
<!--    <p style="text-align: center">工作状态信息</p>-->
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms01taskType"
        label="精密测量子系统任务类型">
      </el-table-column>
      <el-table-column
        prop="ms01startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms01SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms01endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms01Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms02taskType"
        label="信号监测子系统7.3米L天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms02startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms02SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms02endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms02Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms03taskType"
        label="信号监测子系统7.3米C天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms03startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms03SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms03endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms03Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms04taskType"
        label="信号监测子系统13米C/L_1天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms04startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms04SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms04endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms04Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms05taskType"
        label="信号监测子系统13米C/L_2天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms05startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms05SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms05endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms05Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms06taskType"
        label="信号监测子系统MS06天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms06startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms06SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms06endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms06Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms07taskType"
        label="信号监测子系统MS07天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms07startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms07SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms07endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms07Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms08taskType"
        label="信号监测子系统MS08天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms08startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms08SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms08endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms08Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms09taskType"
        label="信号监测子系统MS09天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms09startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms09SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms09endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms09Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms10taskType"
        label="信号监测子系统MS010天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms10startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms10SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms10endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms10Result"
        label="执行结果">
      </el-table-column>

    </el-table>
    <el-table
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms11taskType"
        label="信号监测子系统MS011天线任务类型">
      </el-table-column>
      <el-table-column
        prop="ms11startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms11SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms11endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms11Result"
        label="执行结果">
      </el-table-column>

    </el-table>
  </div>
</template>
<script>
export default {
  name: 'WorkingStateInfo'
}
</script>
<style scoped>

</style>
