<template>
  <div>
    <p style="text-align: center">工作状态信息</p>
    <el-table
      id="table"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms01taskType"
        label="精密测量子系统任务类型">
      </el-table-column>
      <el-table-column
        prop="ms01startTime"
        label="任务开始时间">
      </el-table-column>
      <el-table-column
        prop="ms01SatName"
        label="观测卫星">
      </el-table-column>
      <el-table-column
        prop="ms01endTime"
        label="任务完成时间">
      </el-table-column>
      <el-table-column
        prop="ms01Result"
        label="执行结果">
      </el-table-column>
    </el-table>
    <el-table
      id="table2"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms02taskType"
        label="MS02taskType">
      </el-table-column>
      <el-table-column
        prop="ms02startTime"
        label="MS02startTime">
      </el-table-column>
      <el-table-column
        prop="ms02SatName"
        label="MS02SatName">
      </el-table-column>
      <el-table-column
        prop="ms02endTime"
        label="MS02endTime">
      </el-table-column>
      <el-table-column
        prop="ms02Result"
        label="MS02Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table3"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms03taskType"
        label="MS03taskType">
      </el-table-column>
      <el-table-column
        prop="ms03startTime"
        label="MS03startTime">
      </el-table-column>
      <el-table-column
        prop="ms03SatName"
        label="MS03SatName">
      </el-table-column>
      <el-table-column
        prop="ms03endTime"
        label="MS03endTime">
      </el-table-column>
      <el-table-column
        prop="ms03Result"
        label="MS03Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table4"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms04taskType"
        label="MS04taskType">
      </el-table-column>
      <el-table-column
        prop="ms04startTime"
        label="MS04startTime">
      </el-table-column>
      <el-table-column
        prop="ms04SatName"
        label="MS04SatName">
      </el-table-column>
      <el-table-column
        prop="ms04endTime"
        label="MS04endTime">
      </el-table-column>
      <el-table-column
        prop="ms04Result"
        label="MS04Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table5"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms05taskType"
        label="MS05taskType">
      </el-table-column>
      <el-table-column
        prop="ms05startTime"
        label="MS05startTime">
      </el-table-column>
      <el-table-column
        prop="ms05SatName"
        label="MS05SatName">
      </el-table-column>
      <el-table-column
        prop="ms05endTime"
        label="MS05endTime">
      </el-table-column>
      <el-table-column
        prop="ms05Result"
        label="MS05Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table6"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms06taskType"
        label="MS06taskType">
      </el-table-column>
      <el-table-column
        prop="ms06startTime"
        label="MS06startTime">
      </el-table-column>
      <el-table-column
        prop="ms06SatName"
        label="MS06SatName">
      </el-table-column>
      <el-table-column
        prop="ms06endTime"
        label="MS06endTime">
      </el-table-column>
      <el-table-column
        prop="ms06Result"
        label="MS06Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table7"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms07taskType"
        label="MS07taskType">
      </el-table-column>
      <el-table-column
        prop="ms07startTime"
        label="MS07startTime">
      </el-table-column>
      <el-table-column
        prop="ms07SatName"
        label="MS07SatName">
      </el-table-column>
      <el-table-column
        prop="ms07endTime"
        label="MS07endTime">
      </el-table-column>
      <el-table-column
        prop="ms07Result"
        label="MS07Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table8"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms08taskType"
        label="MS08taskType">
      </el-table-column>
      <el-table-column
        prop="ms08startTime"
        label="MS08startTime">
      </el-table-column>
      <el-table-column
        prop="ms08SatName"
        label="MS08SatName">
      </el-table-column>
      <el-table-column
        prop="ms08endTime"
        label="MS08endTime">
      </el-table-column>
      <el-table-column
        prop="ms08Result"
        label="MS08Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table9"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms09taskType"
        label="MS09taskType">
      </el-table-column>
      <el-table-column
        prop="ms09startTime"
        label="MS09startTime">
      </el-table-column>
      <el-table-column
        prop="ms09SatName"
        label="MS09SatName">
      </el-table-column>
      <el-table-column
        prop="ms09endTime"
        label="MS09endTime">
      </el-table-column>
      <el-table-column
        prop="ms09Result"
        label="MS09Result">
      </el-table-column>
    </el-table>
    <el-table
      id="table10"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms10taskType"
        label="MS10taskType">
      </el-table-column>
      <el-table-column
        prop="ms10startTime"
        label="MS10startTime">
      </el-table-column>
      <el-table-column
        prop="ms10SatName"
        label="MS10SatName">
      </el-table-column>
      <el-table-column
        prop="ms10endTime"
        label="MS10endTime">
      </el-table-column>
      <el-table-column
        prop="ms10Result"
        label="MS10Result">
      </el-table-column>

    </el-table>
    <el-table
      id="table11"
      :data="this.$store.state.WorkingStateInfo"
      header-cell-class-name="tableHeaderCell"
      highlight-current-row
      stripe
      border
      style="width: 100%">
      <el-table-column
        prop="ms11taskType"
        label="MS11taskType">
      </el-table-column>
      <el-table-column
        prop="ms11startTime"
        label="MS11startTime">
      </el-table-column>
      <el-table-column
        prop="ms11SatName"
        label="MS11SatName">
      </el-table-column>
      <el-table-column
        prop="ms11endTime"
        label="MS11endTime">
      </el-table-column>
      <el-table-column
        prop="ms11Result"
        label="MS11Result">
      </el-table-column>

    </el-table>
  </div>
</template>
<script>
export default {
  name: 'WorkingStateInfo',
  methods: {
    datas () {
      return this.$store.getters.getData
    }
  }
}
</script>
<style scoped>

</style>
