export const LIST_COUNT = 10
export const GNSS_SYSTEM_CLOCK_DIFFERENCE_LIST_COUNT = 10
export const RUNTIME_SCROLL_BOARD_LIST_COUNT = 8
export const MIN_WIDTH = 200
export const SPACE_SIGNAL_QUALITY_MONITOR_WORKSTATE_LIST_COUNT = 1
export const NAV_QUALITY_MONITOR_WORKSTATE_LIST_COUNT = 1
export const VIBI_WORKSTATE_LIST_COUNT = 1
export const NAV_SAT_SIGNAL_QUALITY_LIST_COUNT = 1
export const BDS_CLOCK_DIFFERENCE_LIST_COUNT = 1
export const NOTIFICATION_OFFSET = 60
export const SCIENTIFIC_NOTATION_11 = 11
export const SCIENTIFIC_NOTATION_4 = 4
export const SCIENTIFIC_NOTATION_3 = 3
export const EACH_SYSTEM_INFO_PIE_FONT_SIZE = 15
export const SPLANSH_QUERY_PRIOID = 15000
export const SPLANSH_CPU_QUERY_PRIOID = 3000

