export const LIST_COUNT = 10
export const GNSS_SYSTEM_CLOCK_DIFFERENCE_LIST_COUNT = 10
export const MIN_WIDTH = 200
export const SPACE_SIGNAL_QUALITY_MONITOR_WORKSTATE_LIST_COUNT = 1
export const NAV_QUALITY_MONITOR_WORKSTATE_LIST_COUNT = 1
export const VIBI_WORKSTATE_LIST_COUNT = 1
export const NAV_SAT_SIGNAL_QUALITY_LIST_COUNT = 1
export const BDS_CLOCK_DIFFERENCE_LIST_COUNT = 1
